// se baja un archivo json de https://www.mockaroo.com/ 
var personas = [{"id":1,"first_name":"Donn","last_name":"Elsegood","email":"delsegood0@cocolog-nifty.com","gender":"Male"},
{"id":2,"first_name":"Shellie","last_name":"Belham","email":"sbelham1@gizmodo.com","gender":"Female"},
{"id":3,"first_name":"Karel","last_name":"Vass","email":"kvass2@psu.edu","gender":"Female"},
{"id":4,"first_name":"Fifi","last_name":"Sparkwell","email":"fsparkwell3@theatlantic.com","gender":"Female"},
{"id":5,"first_name":"Corry","last_name":"Devons","email":"cdevons4@zimbio.com","gender":"Female"},
{"id":6,"first_name":"Waldemar","last_name":"Wroth","email":"wwroth5@boston.com","gender":"Male"},
{"id":7,"first_name":"Betteann","last_name":"Warters","email":"bwarters6@creativecommons.org","gender":"Female"},
{"id":8,"first_name":"Jessalin","last_name":"Learoyd","email":"jlearoyd7@github.io","gender":"Female"},
{"id":9,"first_name":"Prue","last_name":"Jekel","email":"pjekel8@narod.ru","gender":"Female"},
{"id":10,"first_name":"Brose","last_name":"Kain","email":"bkain9@canalblog.com","gender":"Male"},
{"id":11,"first_name":"Sanford","last_name":"Scibsey","email":"sscibseya@harvard.edu","gender":"Male"},
{"id":12,"first_name":"Milty","last_name":"Sisland","email":"msislandb@comcast.net","gender":"Male"},
{"id":13,"first_name":"Devlen","last_name":"Crudgington","email":"dcrudgingtonc@51.la","gender":"Male"},
{"id":14,"first_name":"Christi","last_name":"Harriday","email":"charridayd@uol.com.br","gender":"Female"},
{"id":15,"first_name":"Brnaba","last_name":"Foy","email":"bfoye@fda.gov","gender":"Male"},
{"id":16,"first_name":"Lissie","last_name":"Copnar","email":"lcopnarf@mayoclinic.com","gender":"Female"},
{"id":17,"first_name":"Tallie","last_name":"Westmancoat","email":"twestmancoatg@instagram.com","gender":"Male"},
{"id":18,"first_name":"Claiborn","last_name":"Diamond","email":"cdiamondh@google.cn","gender":"Male"},
{"id":19,"first_name":"Berny","last_name":"Raw","email":"brawi@live.com","gender":"Female"},
{"id":20,"first_name":"Dorree","last_name":"Sprionghall","email":"dsprionghallj@state.tx.us","gender":"Female"},
{"id":21,"first_name":"Remy","last_name":"Edinburough","email":"redinburoughk@1und1.de","gender":"Female"},
{"id":22,"first_name":"Floyd","last_name":"Lebreton","email":"flebretonl@npr.org","gender":"Male"},
{"id":23,"first_name":"Koressa","last_name":"Monkleigh","email":"kmonkleighm@unc.edu","gender":"Female"},
{"id":24,"first_name":"Krissy","last_name":"Waker","email":"kwakern@answers.com","gender":"Female"},
{"id":25,"first_name":"Maxy","last_name":"Oldland","email":"moldlando@census.gov","gender":"Male"}];